<a href="https://colab.research.google.com/github/GabrielBurack/Machine_learning_course/blob/main/house_price_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# prompt: !pip install plotly --upgrade

!pip install plotly --upgrade


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.8/14.8 MB 78.6 MB/s eta 0:00:00
  Attempting uninstall: plotly
    Found existing installation: plotly 5.24.1
    Uninstalling plotly-5.24.1:
      Successfully uninstalled plotly-5.24.1


In [2]:
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [6]:
base_casas = pd.read_csv('house_prices.csv')
base_casas

id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7   
1             2570      7242     2.0           0     0  ...      7   
2              770     10000     1.0           0     0  ...      6   
3             1960      5000     1.0           0     0  ...      7   
4             1680      8080     1.0           0     0  ...      8   
...            ...       ...     ...         ...   ...  ...    ...   
21608         1530      1131     3.0           0     0  ...      8   
21609         2310      5813     2.0           0     0  ...      8   
21610         1020      1350     2.0           0     0  ...      7   
21611         1600      2388     2.0           0     0  ...      8   
21612         1020      1076     2.0           0     0  ...      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
0            1180              0      1955             0    98178  47.5112   
1            2170            400      1951          1991    98125  47.7210   
2             770              0      1933             0    98028  47.7379   
3            1050            910      1965             0    98136  47.5208   
4            1680              0      1987             0    98074  47.6168   
...           ...            ...       ...           ...      ...      ...   
21608        1530              0      2009             0    98103  47.6993   
21609        2310              0      2014             0    98146  47.5107   
21610        1020              0      2009             0    98144  47.5944   
21611        1600              0      2004             0    98027  47.5345   
21612        1020              0      2008             0    98144  47.5941   

          long  sqft_living15  sqft_lot15  
0     -122.257           1340        5650  
1     -122.319           1690        7639  
2     -122.233           2720        8062  
3     -122.393           1360        5000  
4     -122.045           1800        7503  
...        ...            ...         ...  
21608 -122.346           1530        1509  
21609 -122.362           1830        7200  
21610 -122.299           1020        2007  
21611 -122.069           1410        1287  
21612 -122.299           1020        1357  

[21613 rows x 21 columns]

In [7]:
base_casas.drop('date', axis=1, inplace=True)

In [8]:
base_casas.describe()

id         price      bedrooms     bathrooms   sqft_living  \
count  2.161300e+04  2.161300e+04  21613.000000  21613.000000  21613.000000   
mean   4.580302e+09  5.400881e+05      3.370842      2.114757   2079.899736   
std    2.876566e+09  3.671272e+05      0.930062      0.770163    918.440897   
min    1.000102e+06  7.500000e+04      0.000000      0.000000    290.000000   
25%    2.123049e+09  3.219500e+05      3.000000      1.750000   1427.000000   
50%    3.904930e+09  4.500000e+05      3.000000      2.250000   1910.000000   
75%    7.308900e+09  6.450000e+05      4.000000      2.500000   2550.000000   
max    9.900000e+09  7.700000e+06     33.000000      8.000000  13540.000000   

           sqft_lot        floors    waterfront          view     condition  \
count  2.161300e+04  21613.000000  21613.000000  21613.000000  21613.000000   
mean   1.510697e+04      1.494309      0.007542      0.234303      3.409430   
std    4.142051e+04      0.539989      0.086517      0.766318      0.650743   
min    5.200000e+02      1.000000      0.000000      0.000000      1.000000   
25%    5.040000e+03      1.000000      0.000000      0.000000      3.000000   
50%    7.618000e+03      1.500000      0.000000      0.000000      3.000000   
75%    1.068800e+04      2.000000      0.000000      0.000000      4.000000   
max    1.651359e+06      3.500000      1.000000      4.000000      5.000000   

              grade    sqft_above  sqft_basement      yr_built  yr_renovated  \
count  21613.000000  21613.000000   21613.000000  21613.000000  21613.000000   
mean       7.656873   1788.390691     291.509045   1971.005136     84.402258   
std        1.175459    828.090978     442.575043     29.373411    401.679240   
min        1.000000    290.000000       0.000000   1900.000000      0.000000   
25%        7.000000   1190.000000       0.000000   1951.000000      0.000000   
50%        7.000000   1560.000000       0.000000   1975.000000      0.000000   
75%        8.000000   2210.000000     560.000000   1997.000000      0.000000   
max       13.000000   9410.000000    4820.000000   2015.000000   2015.000000   

            zipcode           lat          long  sqft_living15     sqft_lot15  
count  21613.000000  21613.000000  21613.000000   21613.000000   21613.000000  
mean   98077.939805     47.560053   -122.213896    1986.552492   12768.455652  
std       53.505026      0.138564      0.140828     685.391304   27304.179631  
min    98001.000000     47.155900   -122.519000     399.000000     651.000000  
25%    98033.000000     47.471000   -122.328000    1490.000000    5100.000000  
50%    98065.000000     47.571800   -122.230000    1840.000000    7620.000000  
75%    98118.000000     47.678000   -122.125000    2360.000000   10083.000000  
max    98199.000000     47.777600   -121.315000    6210.000000  871200.000000

##Preparação dos dados

###Obtendo metragem das casas

In [9]:
X_casas = base_casas.iloc[:,3:19].values
X_casas

array([[ 1.00000e+00,  1.18000e+03,  5.65000e+03, ...,  4.75112e+01,
        -1.22257e+02,  1.34000e+03],
       [ 2.25000e+00,  2.57000e+03,  7.24200e+03, ...,  4.77210e+01,
        -1.22319e+02,  1.69000e+03],
       [ 1.00000e+00,  7.70000e+02,  1.00000e+04, ...,  4.77379e+01,
        -1.22233e+02,  2.72000e+03],
       ...,
       [ 7.50000e-01,  1.02000e+03,  1.35000e+03, ...,  4.75944e+01,
        -1.22299e+02,  1.02000e+03],
       [ 2.50000e+00,  1.60000e+03,  2.38800e+03, ...,  4.75345e+01,
        -1.22069e+02,  1.41000e+03],
       [ 7.50000e-01,  1.02000e+03,  1.07600e+03, ...,  4.75941e+01,
        -1.22299e+02,  1.02000e+03]])

###Obtendo o preço das casas

In [10]:
Y_casas = base_casas.iloc[:, 1].values
Y_casas

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

###Dados de treinamento/teste

In [11]:
from sklearn.model_selection import train_test_split
X_casas_treinamento, X_casas_teste, Y_casas_treinamento, Y_casas_teste = train_test_split(X_casas, Y_casas, test_size = 0.30, random_state = 0)

In [12]:
X_casas_treinamento.shape, X_casas_teste.shape

((15129, 16), (6484, 16))

In [13]:
X_casas_treinamento, Y_casas_treinamento

(array([[ 1.50000e+00,  1.39000e+03,  7.20000e+03, ...,  4.77224e+01,
         -1.22332e+02,  1.63000e+03],
        [ 1.50000e+00,  1.45000e+03,  7.31600e+03, ...,  4.77725e+01,
         -1.22349e+02,  1.44000e+03],
        [ 2.75000e+00,  2.86000e+03,  5.37900e+03, ...,  4.77082e+01,
         -1.22104e+02,  2.98000e+03],
        ...,
        [ 2.25000e+00,  2.36000e+03,  1.49500e+04, ...,  4.73856e+01,
         -1.22158e+02,  2.72000e+03],
        [ 2.00000e+00,  2.37000e+03,  7.66650e+04, ...,  4.72831e+01,
         -1.22279e+02,  2.11000e+03],
        [ 2.25000e+00,  2.38000e+03,  1.62360e+04, ...,  4.76126e+01,
         -1.22120e+02,  2.23000e+03]]),
 array([400000., 430000., 720000., ..., 431000., 411000., 699900.]))

In [14]:
X_casas_teste.shape

(6484, 16)

In [15]:
from sklearn.preprocessing import StandardScaler
scaler_x_casas = StandardScaler()
X_casas_treinamento_scaled = scaler_x_casas.fit_transform(X_casas_treinamento)
scaler_y_casas = StandardScaler()
Y_casas_treinamento_scaled = scaler_y_casas.fit_transform(Y_casas_treinamento.reshape(-1,1))

In [16]:
X_casas_treinamento_scaled

array([[-0.79711466, -0.74522967, -0.19007787, ...,  1.17348387,
        -0.83797629, -0.51711194],
       [-0.79711466, -0.68028398, -0.18732779, ...,  1.53476983,
        -0.95879989, -0.7940208 ],
       [ 0.82292131,  0.84593978, -0.23324948, ...,  1.07108346,
         0.78248142,  1.45039839],
       ...,
       [ 0.17490692,  0.30472568, -0.0063437 , ..., -1.25528083,
         0.3986888 ,  1.07147047],
       [-0.14910028,  0.31554996,  1.45677304, ..., -1.99443873,
        -0.46129094,  0.18244729],
       [ 0.17490692,  0.32637425,  0.02414432, ...,  0.38168351,
         0.66876509,  0.35733709]])

In [17]:
Y_casas_treinamento_scaled

array([[-0.38454326],
       [-0.3024967 ],
       [ 0.49062008],
       ...,
       [-0.29976181],
       [-0.35445952],
       [ 0.43564888]])

In [18]:
X_casas_teste_scaled = scaler_x_casas.transform(X_casas_teste)
Y_casas_teste_scaled = scaler_y_casas.transform(Y_casas_teste.reshape(-1,1))

In [19]:
X_casas_teste_scaled.shape, Y_casas_teste_scaled.shape

((6484, 16), (6484, 1))

In [20]:
X_casas_teste_scaled, Y_casas_teste_scaled

(array([[-0.79711466, -0.70193254, -0.32165525, ...,  1.17204161,
         -0.53947092, -0.80859495],
        [ 1.47093569,  2.80513482,  0.86813615, ...,  0.54321655,
          0.35604518,  3.2721672 ],
        [-1.76913625, -0.69110826, -0.2730546 , ...,  0.80065984,
         -1.06540895, -0.7940208 ],
        ...,
        [ 0.49891411,  0.07741576,  0.24863193, ..., -0.78077751,
          0.88909048, -0.19648063],
        [-0.47310747, -0.64781113, -0.1708984 , ..., -1.39878563,
         -0.46839822, -0.28392553],
        [-1.44512905, -0.82099964, -0.141738  , ..., -1.78603226,
          0.22100704, -0.96891061]]),
 array([[-0.66623646],
        [ 2.83715179],
        [ 0.05878167],
        ...,
        [-0.43924097],
        [-0.74554814],
        [-0.91511104]]))

##Treinamento da rede

In [21]:
from sklearn.neural_network import MLPRegressor

In [30]:
regressor_rna_casas = MLPRegressor(max_iter=1000, hidden_layer_sizes=(9,9))
regressor_rna_casas.fit(X_casas_treinamento_scaled, Y_casas_treinamento_scaled.ravel())

MLPRegressor(hidden_layer_sizes=(9, 9), max_iter=2000)

##Resultado


In [31]:
regressor_rna_casas.score(X_casas_treinamento_scaled, Y_casas_treinamento_scaled)

0.8936964728744229

In [24]:
previsoes = regressor_rna_casas.predict(X_casas_teste_scaled).reshape(-1, 1)
previsoes

array([[-0.54584354],
       [ 3.66637726],
       [ 0.09903767],
       ...,
       [-0.38401987],
       [-0.8645717 ],
       [-0.91749571]])

In [25]:
Y_casas_teste_scaled

array([[-0.66623646],
       [ 2.83715179],
       [ 0.05878167],
       ...,
       [-0.43924097],
       [-0.74554814],
       [-0.91511104]])

In [26]:
y_casas_teste_inverse = scaler_y_casas.inverse_transform(Y_casas_teste_scaled)
previsoes_inverse = scaler_y_casas.inverse_transform(previsoes)

In [27]:
y_casas_teste_inverse

array([[ 297000.],
       [1578000.],
       [ 562100.],
       ...,
       [ 380000.],
       [ 268000.],
       [ 206000.]])

In [28]:
previsoes_inverse

array([[ 341021.19509123],
       [1881202.99830339],
       [ 576819.44712207],
       ...,
       [ 400191.37705863],
       [ 224479.50697758],
       [ 205128.0554628 ]])

In [29]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_casas_teste_inverse, previsoes_inverse)

74015.54560055133